### ISSUE TITLE
Add Petri.jl examples

### ISSUE THREAD

**Issue by sdwfrost** [epirecipes/sir-julia#11]
Like ModelingToolkit, Petri.jl offers the ability to generate ODEs, SDEs and jump problems. See [https://github.com/mehalter/Petri.jl/blob/master/examples/epidemiology.jl](https://github.com/mehalter/Petri.jl/blob/master/examples/epidemiology.jl)

**Comment by mehalter** [comment]
I can pick up this issue and put together some examples of generating ODEs, SDEs, and jump problems with Petri.jl

**Comment by sdwfrost** [comment]
Sounds great! My (uncommitted) version of the ODE one (based on yours anyway!) is [here](https://gist.github.com/sdwfrost/86a1719b2d8a71b439618f1575d9436e)

**Comment by sdwfrost** [comment]
As for the AlgebraicJulia one, I think it would probably be best if ODE/SDE/jump system was all in one file to demonstrate the flexibility of the framework. Don't forget to add to the README.md to make sure it's visible. You don't have to worry about getting Binder working, I'll check when I commit with my local package repository.

**Comment by mehalter** [comment]
Yeah that's a good idea. Ill update the AlgebraicPetri PR

**Comment by mehalter** [comment]
Just made a PR with a Petri.jl tutorial similar to how I put together the AlgebraicPetri.jl.

**Comment by sdwfrost** [comment]
Closed with https://github.com/epirecipes/sir-julia/pull/15
