### ISSUE TITLE
Add AlgebraicPetri example

### ISSUE THREAD

**Issue by sdwfrost** [epirecipes/sir-julia#12]
See [https://algebraicjulia.github.io/AlgebraicPetri.jl/dev/examples/covid/epidemiology/](https://algebraicjulia.github.io/AlgebraicPetri.jl/dev/examples/covid/epidemiology/)

**Comment by mehalter** [comment]
Added some examples with #8

**Comment by sdwfrost** [comment]
Closed with https://github.com/epirecipes/sir-julia/pull/8
