### ISSUE TITLE
Add continuous time ABM using Agents.jl

### ISSUE THREAD

**Issue by sdwfrost** [epirecipes/sir-julia#153]

**Comment by sdwfrost** [comment]
Added a first draft [here](https://github.com/epirecipes/sir-julia/blob/master/markdown/des_agentsjl/des_agentsjl.md) - I haven't linked it to the README.md yet, as the peak infected comes too late. Any ideas where I'm going wrong @slwu89?

**Comment by slwu89** [comment]
This is weird, I played around with it a bit to no avail. Also, I didn't know Agents.jl now supports continuous time simulations, let me look at the documentation a bit more.

**Comment by sdwfrost** [comment]
Thanks @slwu89! I can't see where it's going wrong. I'll file an issue at Agents.jl, if you think there's nothing obvious I've overlooked.

**Comment by slwu89** [comment]
@sdwfrost I am reading https://juliadynamics.github.io/Agents.jl/stable/api/#Agents.EventQueueABM in detail again. Particularly the part on "propensity". Is it the case that for events which are not "enabled", the propensity should be zero? So there needs to be a check of the agent's state in the propensity function as well?

**Comment by slwu89** [comment]
Ok yes @sdwfrost that did the trick. See below

```julia
function transmit!(agent, model)
    # Choose random individual
    alter = random_agent(model)
    if alter.status == :I && (rand() ≤ model.β)
        # An infection occurs
        agent.status = :I
    end
end;

function recover!(agent, model)
    agent.status = :R
end;

function transmit_propensity(agent, model)
    if agent.status == :S
        return model.c
    else
        return 0.0
    end
end

function recovery_propensity(agent, model)
    if agent.status == :I
        return model.γ
    else
        return 0.0
    end
end;
```

![image](https://github.com/user-attachments/assets/ab9fbd3f-8343-4e64-90d0-da9f1cb9bffa)

**Comment by slwu89** [comment]
Opened PR https://github.com/epirecipes/sir-julia/pull/156

**Comment by sdwfrost** [comment]
Thanks @slwu89!
