### ISSUE TITLE
Plots not working in Turing example

### ISSUE THREAD

**Issue by arnaudmgh** [epirecipes/sir-julia#18]
In https://github.com/epirecipes/sir-julia/blob/master/markdown/ode_turing/ode_turing.md at the end, there are error messages in place of the (most interesting :) ) plots

**Comment by sdwfrost** [comment]
Thanks! I try to keep my packages up to date, but sometimes things break. I'll fix in the next update.

**Comment by arnaudmgh** [comment]
You're welcome - and thanks for you useful resource!

**Comment by sdwfrost** [comment]
Lots of updates since then - many things are still not updated and hence broken with the latest release, but I will get round to updating...
