### ISSUE TITLE
Fix AlgebraicPetri.jl example

### ISSUE THREAD

**Issue by sdwfrost** [epirecipes/sir-julia#33]
[https://github.com/epirecipes/sir-julia/blob/master/markdown/pn_algebraicpetri/pn_algebraicpetri.md](https://github.com/epirecipes/sir-julia/blob/master/markdown/pn_algebraicpetri/pn_algebraicpetri.md) no longer runs with the latest `AlgebraicPetri.jl`, as the API has changed. Can you fix @mehalter?

**Comment by mehalter** [comment]
@sdwfrost Yeah I'll do this today.
