### ISSUE TITLE
Add Sellke construction

### ISSUE THREAD

**Issue by sdwfrost** [epirecipes/sir-julia#37]

**Comment by slwu89** [comment]
@sdwfrost I was browsing this repo and noticed this issue...I happened to code up a simple Sellke method to draw SIR epidemic final size previously in some simple Julia, as such:

```
function run_Sellke_SIR_finalsize(u0,p)
    (S,I,R) = u0
    N = S+I+R
    (β,c,γ) = p
    λ = β*c/N

    Q = rand(Exponential(),S)
    sort!(Q)

    T0 = rand(Exponential(1/γ),I)
    T = rand(Exponential(1/γ),S)

    ST0 = sum(T0)
    Y = [ST0; ST0 .+ cumsum(T[1:end-1])]

    Z = findfirst(Q .> Y*λ)

    if Z == nothing
        return S+I
    else
        return Z+I-1
    end
end
```

I believe it to be correct, as I tested against the exact solution from "Stochastic Epidemic Models and Their Statistical Analysis".

**Comment by sdwfrost** [comment]
Closed with PR https://github.com/epirecipes/sir-julia/pull/40
