### ISSUE TITLE
Add InfiniteArrays.jl example

### ISSUE THREAD

**Issue by sdwfrost** [epirecipes/sir-julia#39]
Add an example with InfiniteArrays.jl to implement an SIR model with counting of the number of people someone infects.

**Comment by slwu89** [comment]
@sdwfrost this sounds quite interesting, what ideas did you have for how to implement that with InfiniteArrays.jl?

**Comment by sdwfrost** [comment]
Closed with https://github.com/epirecipes/sir-julia/commit/b8065866bc2fa3c5ef4c8b9cf4b2138c8524c9e2
