### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by DanielVandH** [epirecipes/sir-julia#78]
Interesting work! It was cool to see what you could do with my ProfileLikelihood.jl.

I noticed in the README it says that "GitHub Markdown doesn't parse equations, so here's a description of the underlying SIR model.". This isn't true anymore, so that e.g.

```
$$
\begin{align*}
\dfrac{\mathrm dS}{\mathrm dt} &= -\frac{\beta I S}{N}, \\
\dfrac{\mathrm dI}{\mathrm dt} &= \frac{\beta I S}{N} - \gamma I,\\ 
\dfrac{\mathrm dR}{\mathrm dt} &= \gamma I, \\
S(t) + I(t) + R(t) &= N, \\
S(0) &= 990, \\
I(0) &= 10, \\
R(0) &= 10.
\end{align*}
$$
```

(or whatever parametrisation you'd use) should parse correctly.

**Comment by sdwfrost** [comment]
Done! Thanks for the information.
